# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b78cd2a8dd2007a57c03104280f2e29e15d301141ee099590aaa5e471b33b034ac7c509555cbe3664a792cd0a2f02db90563bfdde5174798d25d44888dbf0c4b

test:
  secret_key_base: fb1673102ba276e649b890e7d815a2c3cc9085d8ab23c75e1f04969d154218501d8dec6c15d8039e9274cc6e89799575ff50140d440146de72c9dc111ad00fc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
